[workspace]
members = [
    "crates/assets",
    "crates/icons",
    "crates/theme",
    "crates/macros",
    "crates/vektra",
    "docs/preview",
    "examples",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.98.0"

[workspace.dependencies]
allocation-counter = "0.8.1"
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support"] }
gpui = { git = "https://github.com/zed-industries/zed", rev = "fd82517a115d97a07835b52f0512b22b38e38ccf" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "fd82517a115d97a07835b52f0512b22b38e38ccf", package = "gpui_platform" }
gpui_web = { git = "https://github.com/zed-industries/zed", rev = "fd82517a115d97a07835b52f0512b22b38e38ccf", default-features = false }
hashbrown = { version = "0.17", default-features = false, features = ["allocator-api2", "default-hasher", "inline-more"] }
heck = "0.5"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
rust-embed = { version = "=8.12.0", features = ["include-exclude"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
syn = { version = "3", features = ["derive", "parsing", "printing", "proc-macro"] }
thiserror = "2"
trybuild = "1"
unicode-script = "0.5"
unicode-segmentation = "1.13.3"
vektra-assets = { path = "crates/assets" }
vektra-icons = { path = "crates/icons" }
vektra-macros = { path = "crates/macros" }
vektra-theme = { path = "crates/theme" }
vektra = { path = "crates/vektra" }

[profile.dev]
codegen-units = 16
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package]
resvg = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
taffy = { opt-level = 3 }
ttf-parser = { opt-level = 3 }
smol = { opt-level = 3 }
gpui = { opt-level = 3 }
gpui_platform = { opt-level = 3 }
gpui_macros = { opt-level = 3 }
sum_tree = { opt-level = 3 }
