use super::{PreviewApp, PreviewLang};
use gpui::{Context, ElementId, IntoElement, ParentElement, Styled, Window, div, px};
use vektra::{
    Button, ScrollGutter, ScrollVisibility, ScrollbarConfig, VirtualList, VirtualListState,
};

const ITEM_COUNT: usize = 1_000_000;

pub(crate) struct VirtualListDemo {
    state: VirtualListState,
}

impl VirtualListDemo {
    pub(crate) fn new() -> Self {
        Self {
            state: VirtualListState::new(),
        }
    }

    pub(crate) fn render(
        &self,
        language: PreviewLang,
        window: &mut Window,
        cx: &mut Context<PreviewApp>,
    ) -> impl IntoElement {
        let (title, hint, start, jump) = match language {
            PreviewLang::ZhCn => (
                "1,000,000 项 VirtualList",
                "按索引生成，不构建百万项 Vec；只物化视口行，缓存上限为 0。",
                "返回开头",
                "跳到第 900,000 项",
            ),
            PreviewLang::EnUs => (
                "1,000,000-item VirtualList",
                "Generated by index without a million-item Vec; only viewport rows are materialized and the row cache limit is zero.",
                "Back to start",
                "Jump to item 900,000",
            ),
        };
        let theme = vektra::current_theme(window, cx);
        let metrics = self.state.metrics();
        // #region virtual-list-example-basic
        let list = VirtualList::new(
            "preview-million-virtual-list",
            self.state.clone(),
            ITEM_COUNT,
            px(30.),
            |index| ElementId::named_usize("preview-million-row", index),
            |index, _, _| {
                div()
                    .w_full()
                    .h_full()
                    .flex()
                    .items_center()
                    .px(px(8.))
                    .child(format!("Item {index:07}"))
            },
        )
        .aria_label(title)
        .scrollbar(
            ScrollbarConfig::new()
                .visibility(ScrollVisibility::Always)
                .gutter(ScrollGutter::Stable),
        );
        // #endregion virtual-list-example-basic

        div()
            .size_full()
            .flex()
            .flex_col()
            .items_center()
            .justify_center()
            .gap(px(10.))
            .p(px(18.))
            .bg(theme.semantic.background)
            .text_color(theme.semantic.foreground)
            .child(div().text_size(px(18.)).child(title))
            .child(hint)
            .child(format!(
                "visible {}..{} · materialized {} · cache {}/{}",
                metrics.visible_range.start,
                metrics.visible_range.end,
                metrics.materialized_rows,
                metrics.cached_rows,
                metrics.max_cached_rows,
            ))
            .child(div().w_full().max_w(px(420.)).h(px(240.)).child(list))
            .child(
                div()
                    .flex()
                    .gap(px(8.))
                    .child(
                        Button::new("preview-virtual-start")
                            .label(start)
                            .on_click_in(cx, |this, _, _, cx| {
                                this.virtual_list_demo.state.scroll_to_start();
                                cx.notify();
                            }),
                    )
                    .child(Button::new("preview-virtual-jump").label(jump).on_click_in(
                        cx,
                        |this, _, _, cx| {
                            this.virtual_list_demo.state.scroll_to_index(900_000);
                            cx.notify();
                        },
                    )),
            )
    }
}
